version: '3'
services:

  #Nginx Service VueJS
  vuejs-webserver:
    image: nginx:1.18.0-alpine
    container_name: vuejs-webserver
    restart: always
    tty: true,
    environment:
      VIRTUAL_HOST: ${VIRTUAL_HOST}
      LETSENCRYPT_HOST: ${LETSENCRYPT_HOST}
      LETSENCRYPT_EMAIL: ${LETSENCRYPT_EMAIL}
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./src:/var/www
      - ./nginx/conf.d/:/etc/nginx/conf.d/
    networks:
      - webproxy
      - client-network
  
  #Node Service VueJS
  vuejs-npm:
    build:
      context: .
      dockerfile: Dockerfile
    image: vuejs_node_custom
    container_name: vuejs-npm
    volumes:
      - ./src:/var/www
    working_dir: /var/www
    depends_on:
      - vuejs-webserver
    entrypoint: ['npm'] #can be overriden like this: docker-compose -f docker-compose-dev.yml run --entrypoint "vue --version" --rm vuejs-npm
    networks:
      - client-network

#Docker Networks
networks:
  webproxy:
    external:
      name: webproxy
  client-network:
    driver: bridge